In [17]:
import numpy as np
import re
import os
import sys
import subprocess
import pandas as pd

In [43]:
subprocess.run('mv ../rejected_results/* ../results',shell=True)
#Sample filter function
def filter_single_video(video_times, rating_times, video_order, scores,attentions):
    #First check if user watching alines with video length
    #0.5 sec tolerance for black screen at the end
    ret = 0
    bad = 0
    violate = 0
    a = 0
    for k in video_times[:-1]:
        if k < 10000:
            a += 1
    if video_times[-1] < 7000:
        a +=1
    if scores[-1] != max(scores):
        a+=1
    #if scores[3] > scores[2] or scores[1] > scores[0]:
    #    a+=1

    if a >0:
        return 1
    return 0 #We don't move this user to rejected folder

#Parse data from user result file 
def parse_results(lines):
    #video_times = list(map(int,lines[2].strip().split(','))) #read times spent on each video  
    #rating_times = list(map(int,lines[3].strip().split(','))) #read times spent on each rating  
    video_times = []; rating_times = []
    video_order = list(map(int,lines[1].strip().split(','))) #read the video order seen by the surveyee
    scores = list(map(int,lines[0].strip().split(','))) #read scores
    attentions = list(map(int,lines[-1].strip().split(','))) #attention checks    
    video_times =  list(map(int,lines[2].strip().split(','))) 
    return video_times, rating_times, video_order, scores, attentions


#input from the cmd line script
result_path = '../results/'
#white_list = '../good/'


move = False
result_files = os.listdir(result_path)
#white_list_files = os.listdir(white_list)

total = 0
approved = 0
reject = 0
pending = 0
for result_file in result_files:
    #filter a single result
    total +=1
    '''
    if result_file in white_list_files:
        approved +=1
        continue
    '''
    result = result_path + result_file
    #print(result)
    with open(result, "r") as fp:
        lines = fp.readlines()
        move = False

        #insert customized filter here 
        move = filter_single_video(*parse_results(lines))
        if move == 1:
            reject +=1
            print(result_file)
            os.system("mv {} ../rejected_results/".format(result))
        else:
            approved +=1

print('reject:',reject)
print('approved:',approved)
print('rejection ratio:', reject/(reject+approved))

[1625229551377]
[1625189711242]
[1625199540695]
[1625184949072]
[1625200077038]
[1625212551365]
AHV4U78TUUDKI.txt
[1625184217777]
[1625183861399]
[1625193252089]
[1625187362807]
[1625203064790]
[1625201442147]
[1625192640337]
[1625202598089]
[1625183855524]
[1625187384379]
A1IZ4NX41GKU4X.txt
[1625232680514]
[1625211091921]
[1625215794000]
[1625183891769]
[1625230546663]
A3HALUPLZ4IKYJ.txt
[1625203017413]
A3SLY0SJLJZ0J1.txt
[1625189391353]
[1625183782373]
[1625237562147]
[1625194692695]
[1625229873637]
[1625201667806]
[1625193461958]
[1625184400127]
[1625203481106]
[1625202102881]
[1625195875196]
[1625189425771]
[1625189906588]
[1625187213936]
[1625187254542]
[1625197628574]
[1625212430770]
[1625215016667]
A3VOMP0WOJTB4I.txt
[1625193280529]
[1625204333638]
[1625196070947]
[1625236132240]
[1625187839743]
[1625231816078]
[1625183895500]
reject: 5
approved: 42
rejection ratio: 0.10638297872340426

In [36]:
subprocess.run('python3 ./create_csv.py',shell=True, cwd="/tank/yiyangou/web_QoE")

CompletedProcess(args='python3 ./create_csv.py', returncode=0)

In [38]:
df = pd.read_csv('../sum.csv',header=None)
columns = ['scores','video_order','time']
df = df[[0,1,2]]
df.columns = columns
df

       scores video_order                            time
0   5,5,4,4,5   1,2,4,3,5   34746,22619,19535,21958,16037
1   1,1,2,2,5   3,4,1,2,5   13670,13751,17684,15461,10827
2   4,4,5,5,1   4,3,2,1,5        1245,1313,1137,14432,750
3   1,3,1,1,5   4,3,1,2,5   15189,13726,15243,18494,13227
4   3,4,4,4,5   4,3,2,1,5   15904,19547,16024,27946,17058
5   2,2,2,2,5   1,2,4,3,5    14620,13373,16835,14381,9816
6   2,2,2,1,5   4,3,2,1,5   15453,12494,15366,12386,10005
7   4,4,4,4,4   3,4,1,2,5   12245,14330,27825,27561,39912
8   4,4,4,3,5   4,3,2,1,5   16635,16972,18679,24464,14409
9   4,5,5,4,5   2,1,3,4,5   17126,17546,17503,23102,12842
10  4,2,4,5,5   1,2,3,4,5   40471,22872,22493,18145,15747
11  2,4,2,2,5   3,4,1,2,5   16151,16069,49743,17974,12257
12  1,2,2,2,5   1,2,4,3,5   22116,23819,17623,17676,14631
13  1,1,1,1,5   4,3,2,1,5   15669,14681,16270,18827,12280
14  4,4,4,5,5   3,4,1,2,5   16013,15641,16603,16570,13009
15  1,2,1,1,5   3,4,1,2,5   20480,18093,20609,20235,19727
16  4,4,2,3,5   1,2,4,3,5   19036,17735,17662,17335,14354
17  3,4,3,4,5   4,3,2,1,5   16124,18080,17202,17821,12758
18  4,5,4,5,5   3,4,1,2,5   18570,16522,25103,18197,14763
19  3,4,3,4,5   2,1,3,4,5   21794,40405,20953,20169,22661
20  4,5,4,5,5   3,4,1,2,5   15606,15360,17098,31374,26649
21  3,3,2,4,5   4,3,2,1,5   16578,20340,20024,23269,13434
22  4,5,3,3,5   2,1,4,3,5   12206,19710,18814,17600,10549
23  2,2,2,2,5   1,2,4,3,5   15421,13045,11677,13227,10691
24  4,3,4,3,5   3,4,1,2,5   19422,18402,44888,16583,14793
25  1,1,1,2,5   4,3,1,2,5   35418,40183,27901,49667,52516
26  2,2,2,1,5   3,4,1,2,5   16242,16998,17057,17716,15955
27  5,5,4,4,5   3,4,2,1,5   20517,10871,21235,18864,19083
28  2,2,2,2,5   1,2,4,3,5   21280,18470,21914,16790,12693
29  2,2,2,2,5   1,2,4,3,5   17915,31635,24652,35090,29777
30  2,2,2,2,5   2,1,4,3,5   17040,18210,22260,16838,13979
31  3,3,4,4,5   2,1,3,4,5   19273,21054,18892,34990,15738
32  4,4,4,4,4   3,4,2,1,5  15001,16239,134078,22700,18503
33  3,2,2,1,5   3,4,2,1,5   14649,15693,16830,13931,10779
34  3,2,2,3,5   4,3,2,1,5   22683,30165,28505,85474,16409
35  4,4,5,4,5   3,4,2,1,5   12766,14391,14272,14487,11716
36  3,4,3,3,5   2,1,4,3,5   19302,35035,17119,19949,13691
37  3,2,4,3,5   4,3,1,2,5   20116,19176,20148,19657,13448
38  2,4,4,4,4   2,1,4,3,5   15884,14943,15442,17608,17845
39  2,1,2,2,5   3,4,2,1,5   14141,13846,20457,14945,11141
40  5,5,4,4,5   2,1,4,3,5   16947,17400,24250,20669,17006
41  4,4,5,4,5   2,1,3,4,5   20662,44371,20387,30719,14839
42  2,2,2,2,5   2,1,3,4,5    12367,15470,13284,12927,9064